version: "3"
services:
  app:
    image: fitup.dev:latest
    volumes:
      - "./:/go/src/fitup/"
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo:4.0.4-xenial
    ports:
      - "27017:27017"
    volumes:
      - fitup:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
volumes:
  fitup:
